function handler() {
  cd vice

  ./x128 -silent -sound -keybuf "10 graphic 1
    20 scnclr
    30 circle 1,100,100,20
    run
  " +warp -limitcycles 8000000 -exitscreenshotvicii /tmp/$1.png 2>&1 >/dev/null
  cd ..
#  echo "{\"isBase64Encoded\": true, \"statusCode\": 200, "headers": {\"content-type\":\"image/png\"}, \"body\": \"`base64 /tmp/$1.png`\"}"
  echo "{\"isBase64Encoded\": true, \"headers\": {\"Content-type\": \"image/png\", \"content-disposition\":\"attachment; filename=$1.png\"}, \"statusCode\":200, \"body\": \"iVBORw0KGgoAAAANSUhEUgAAAYAAAAEQCAYAAAC5oaP8AAAD40lEQVR42u3dMa6CQBRAUTFsjY41UbAmOno61oSdIRQK4ugM75waDZmfvDt8RKt5mZYbAOHcLQGAAAAgAAAIAAACAIAAACAAAAgAAAIAgAAAIAAACAAAAgCAAAAgAAAIAAACAIAAACAAAAgAAAIAgAAAIAAACACAAAAgAAAIAAACAIAAACAAAAgAAAIAgAAAIAAAZKX+9wkM/eivAITUdo0rAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABACA12pLEFvbNW+PGfrRQoEAcLWhv2e4Hz0eEAAKH/zbY9uueb6HEIAAUNDgPzu0168XAhAAChj+KYb0+qpABKBMPgVk+J8OwZ4byYAAcKHhLwIgAAQe/iIAAkDg4S8CIAAEHv4iAAIAgAAQbffvKgAEAAAB4Fe7f+cFCEBQuT2N6+lgEAAABIAUcv4uHjeDQQAAEAAABAAAAQBAAAAQAAAEAAABAEAAuOX9sJUfjAcBAEAASLnbdj6AAAST83cBAQIAgACQaredy79d3PwFAQBAAIhyFWD3DwJAwAgY/iAABIyA4Q8CQMAIGP4gAASMgOEP5aotQZwIfHNQp3hPQABIEIH10P50cJ99PSAAZBCCIzt4gx8EgIuFYDvc9xwPCAAXjAEQi08BAQgAAAIAgAAAIAAACAAAAgCAAAAgAAAIAAACAIAAACAAAAgAAAIAgAAAIAAACAAAAgCAAAAgAAAIAAACAIAAAAgAAAIAgAAAIAAACAAAAgCAAAAgAAAIAAACAIAAACAAAAgAAAIAgAAAIAAACAAAAgCAAAAgAAAIAAACAIAAAAiAJQAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQAQAAAEAAABAEAAABAAAAQAAAEAoCzVvEyLZQBwBQCAAAAgAAAIAAACAIAAACAAAAgAAAIAgAAAIAAACAAAAgCAAAAgAAAIAAACAIAAACAAAAgAAAIAgAAAIAAAAgCAAAAgAAAIAAACAIAAACAAAAgAAAIAgAAAIAAACAAAAgDArzwAZ3et/aP/o+oAAAAASUVORK5CYII=\"}"
#  echo "{\"event_data\":\"$2\", \"status\": \"SUCCESS\", \"data\": \"`base64 /tmp/$1.png`\"}"
#  echo "/tmp/$1.png"
}
